<course name="Programming Languages" type='Lecture' type='olala'>
<class instructor="Husnu Yenigun" section='0' instructor='kerem'  crn=20258>
<meeting day=R start=08:40 end=10:30/>
<meeting start=08:40 end=09:30 day=F/>
</class>
<class instructor="Husnu Yenigun" section='0' instructor='kerem'  crn=20258>
<meeting day=R start=08:40 end=10:30/>
<meeting start=12:12 start=08:40 end=09:30/>
</class>
</course>
